<?php
class Cylinder extends Circle{
    public float $heigth;
    public function __construct($radius, $color,$heigth)
    {
        parent::__construct($radius, $color);
        $this->heigth=$heigth;
    }
    public function thetichHinhTru(): float|int
    {
        return parent::circleArea()*$this->heigth; // TODO: Change the autogenerated stub
    }

    public function toString()
    {
        echo "<br>"."Bán kính : ".$this->radius."<br>"."Color : ".$this->color."<br>";
        echo "Chiều cao = ".$this->heigth;// TODO: Change the autogenerated stub
        echo "<br>";
        echo "Diện tích đáy : ". parent::circleArea();
        echo "<br>";
        echo "Thể tích hình trụ là : ".Cylinder::thetichHinhTru();
    }
}
